# -*- coding: utf-8 -*-
"""training

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hS6RYHr6oORAde6XZfh8W7k-ctDciFPo
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="MwuNnjPktvGiGeyTCFvT")
project = rf.workspace("dhaksana-e11fm").project("pallet-detection-qanxs")
version = project.version(3)
dataset = version.download("yolov8")

!pip install opencv-python ultralytics

from ultralytics import YOLO
model = YOLO("yolov8l.pt")  # load a pretrained model (recommended for training)

custom_data_yaml="/content/Pallet-Detection-3/data.yaml"  # path to your custom data yaml file

results=model.train(data=custom_data_yaml, epochs=50,imgsz=640)  # train the model

validation_results = model.val(data=custom_data_yaml)  # validate the model on the validation set

import shutil
import os

# Create the folder if it doesn't exist
os.makedirs("/content/drive/MyDrive/yolov", exist_ok=True)

# Define paths
source_path = "runs/detect/train/weights/best.pt"
destination_path = "/content/drive/MyDrive/yolov/best.pt"

# Copy the file
shutil.copy(source_path, destination_path)